### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by Asd6600** [Asd5500/AsadSQA#1]
Few mistakes in the code were there and it was corrected. Rest all are correct 

> <html>
> 
> 
> 
> <head>
> 
> <title> home page </title>
> 
> 
> 
> <style>
> 
> body {margin:0;}
> 
> 
> 
> .navbar {
> 
>   overflow: hidden;
> 
>   background-color: ivory;
> 
>   position: fixed;
> 
>   top: 0;
> 
>   width: 100%;
> 
> }

**Comment by Asd5500** [comment]
thank you

**Comment by Asd5500** [comment]
<html>

<head>
<title> Contact us page </title>

<style>
body {margin:0;}

.navbar {
  overflow: hidden;
  background-color: ivory;
  position: fixed;
  top: 0;
  width: 100%;
}

**Comment by Asd5500** [comment]
> t
